spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ec-202107c
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: masahiro.fukushima@rakus-partners.co.jp
    password: phqztmndgeucfhyv
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true    